---
- name: percona
  hosts: all
  user: root
  become: true
  roles:
  - percona
  handlers:
  - include: handlers/main.yml
  vars_files:
  - vars/local.yml
  - vars/versions.yml
  - vars/my.cnf.yml
  - vars/my.rds.cnf.yml
  - vars/secrets.yml
  - vars/vault.yml
