---
- name: add percona deb repository
  apt_repository: repo='deb http://repo.percona.com/apt {{ ubuntu_version_name }} main'
                  state=present
                  mode=644


- name: add percona deb source repository
  apt_repository: repo='deb-src http://repo.percona.com/apt {{ ubuntu_version_name }} main'
                  state=present
                  mode=644
