---
- name: install percona dependencies
  apt: name={{ item }}
       update_cache=yes
       state=present

  with_items:
  - python-mysqldb


- name: copy my.cnf file
  template: src=templates/my.cnf.j2
            dest=/etc/mysql/my.cnf
            owner=root
            group=root
            mode=0644

  notify: restart mysql
  tags:
  - configuration_files
  - my_cnf
