---
- name: update mysql root password for all root accounts
  mysql_user: name=root
              host={{ item }}
              password={{ mysql_root_password }}

  with_items:
  - "{{ ansible_hostname }}"
  - 127.0.0.1
  - ::1
  - localhost


- name: copy root my.cnf file with root password credentials
  template: src=templates/root.my.cnf.j2
            dest=/root/.my.cnf
            owner=root
            group=root
            mode=0600


- name: delete the MySQL test database
  mysql_db: db=test
            state=absent


- name: delete anonymous MySQL server user for localhost
  mysql_user: user=""
              state=absent


- name: delete anonymous MySQL server user for hostname
  mysql_user: user=""
              host="{{ ansible_hostname }}"
              state=absent


- name: make new database user
  mysql_user: name={{ db_user }}
              password={{ db_user_password }}
              priv=*.*:ALL
              login_host={{ mysql_host }}
              login_user={{ mysql_root_user }}
              login_password={{ mysql_root_password }}
              state=present
